In [11]:
%matplotlib inline
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [12]:
import sys
sys.path.append('../../')
import numpy as np
import pandas as pd

from probabilistic.capabilities.uncertainty_definitions import (NormalDistribution, UniformDistribution,
                                                                LognormalDistribution, TruncatedNormalDistribution, 
                                                                TruncatedLognormalDistribution, DeterministicCharacterization)
from probabilistic.capabilities.sampling import OneAtATimeSensitivityStudy, BoundingStudy

In [13]:
study_parameters = {}
study_parameters['parameter_1'] = NormalDistribution(name='parameter 1',
                                                     uncertainty_type='aleatory',
                                                     nominal_value=5,
                                                     mean=5,
                                                     std_deviation=1)

study_parameters['parameter_2'] = TruncatedNormalDistribution(name='parameter 2',
                                                              uncertainty_type='epistemic',
                                                              nominal_value=5,
                                                              mean=5,
                                                              std_deviation=1,
                                                              lower_bound=3,
                                                              upper_bound=7)

study_parameters['parameter_3'] = LognormalDistribution(name='parameter 3',
                                                        uncertainty_type='epistemic',
                                                        nominal_value=1,
                                                        mu=-.3,
                                                        sigma=.3)

study_parameters['parameter_4'] = TruncatedLognormalDistribution(name='parameter 4',
                                                              uncertainty_type='aleatory',
                                                              nominal_value=1,
                                                              mu=-.3,
                                                              sigma=.3,
                                                              lower_bound=0.4,
                                                              upper_bound=1.2)

study_parameters['parameter_5'] = UniformDistribution(name='parameter 5',
                                                      uncertainty_type='aleatory',
                                                      nominal_value=2,
                                                      lower_bound=0,
                                                      upper_bound=5)

study_parameters['deterministic_1'] = DeterministicCharacterization(name='deterministic 1',
                                                                    value=5)

In [14]:
bounding_sensitivity_study = BoundingStudy(number_of_aleatory_samples=1,
                                           number_of_epistemic_samples=1,
                                           random_state=np.random.default_rng())
bounding_sensitivity_study.add_variables(study_parameters)
bounding_study_samples = bounding_sensitivity_study.create_variable_sample_sheet()

one_at_a_time_sensitivity_study = OneAtATimeSensitivityStudy(number_of_aleatory_samples=5,
                                                             number_of_epistemic_samples=2,
                                                             random_state=np.random.default_rng())
one_at_a_time_sensitivity_study.add_variables(study_parameters)
one_at_a_time_study_samples = one_at_a_time_sensitivity_study.create_variable_sample_sheet()

In [15]:
pd.DataFrame(bounding_study_samples)

,parameter 1,parameter 4,parameter 5,parameter 2,parameter 3,deterministic 1
0,2.673652,1.000000,2.00,5.000000,1.000000,5.0
1,7.326348,1.000000,2.00,5.000000,1.000000,5.0
2,5.000000,0.419937,2.00,5.000000,1.000000,5.0
3,5.000000,1.171774,2.00,5.000000,1.000000,5.0
4,5.000000,1.000000,0.05,5.000000,1.000000,5.0
5,5.000000,1.000000,4.95,5.000000,1.000000,5.0
6,5.000000,1.000000,2.00,3.151916,1.000000,5.0
7,5.000000,1.000000,2.00,6.848084,1.000000,5.0
8,5.000000,1.000000,2.00,5.000000,0.368651,5.0
9,5.000000,1.000000,2.00,5.000000,1.488702,5.0

In [16]:
pd.DataFrame(one_at_a_time_study_samples)

,parameter 1,parameter 4,parameter 5,parameter 2,parameter 3,deterministic 1
0,3.559344,1.000000,2.000000,5.000000,1.000000,5.0
1,4.367546,1.000000,2.000000,5.000000,1.000000,5.0
2,4.930551,1.000000,2.000000,5.000000,1.000000,5.0
3,5.678712,1.000000,2.000000,5.000000,1.000000,5.0
4,6.716067,1.000000,2.000000,5.000000,1.000000,5.0
5,5.000000,0.494822,2.000000,5.000000,1.000000,5.0
6,5.000000,0.613065,2.000000,5.000000,1.000000,5.0
7,5.000000,0.717406,2.000000,5.000000,1.000000,5.0
8,5.000000,0.879062,2.000000,5.000000,1.000000,5.0
9,5.000000,1.099931,2.000000,5.000000,1.000000,5.0
10,5.000000,1.000000,0.374205,5.000000,1.000000,5.0
11,5.000000,1.000000,1.317726,5.000000,1.000000,5.0
12,5.000000,1.000000,2.361580,5.000000,1.000000,5.0
13,5.000000,1.000000,3.756699,5.000000,1.000000,5.0
14,5.000000,1.000000,4.784626,5.000000,1.000000,5.0
15,5.000000,1.000000,2.000000,3.294768,1.000000,5.0
16,5.000000,1.000000,2.000000,5.242002,1.000000,5.0
17,5.000000,1.000000,2.000000,5.000000,0.405642,5.0
18,5.000000,1.000000,2.000000,5.000000,0.799423,5.0